### ISSUE TITLE
SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by Marcel-Fontys** [onecuriousmindset/brainstorm-ideas-using-ai#1]
I get the error "SyntaxError: Unexpected token '?'"

```
npm run start

> brainstorm-ideas-using-ai@1.0.0 start
> concurrently "npm run start --workspace client" "npm run start --workspace server"

/home/marcel/ff/brainstorm-ideas-using-ai/node_modules/concurrently/dist/bin/concurrently.js:218
const additionalArguments = lodash_1.default.castArray(args['--'] ?? []).map(String);
                                                                   ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

```

**Comment by onecuriousmindset** [comment]
hey, seems like it's coming from your node.js version. It should work well on node 20 or above. Which version are you using ?
